/* Generated By:JavaCC: Do not edit this line. MusyConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MusyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PART = 5;
  /** RegularExpression Id. */
  int NOTE = 6;
  /** RegularExpression Id. */
  int QUARTER = 7;
  /** RegularExpression Id. */
  int HALF = 8;
  /** RegularExpression Id. */
  int WHOLE = 9;
  /** RegularExpression Id. */
  int COMP = 10;
  /** RegularExpression Id. */
  int DISP = 11;
  /** RegularExpression Id. */
  int PLAY = 12;
  /** RegularExpression Id. */
  int TO = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int RPAR = 16;
  /** RegularExpression Id. */
  int LBRAC = 17;
  /** RegularExpression Id. */
  int RBRAC = 18;
  /** RegularExpression Id. */
  int PIPE = 19;
  /** RegularExpression Id. */
  int COLON = 20;
  /** RegularExpression Id. */
  int NUMBER = 21;
  /** RegularExpression Id. */
  int ADDN = 22;
  /** RegularExpression Id. */
  int NEWS = 23;
  /** RegularExpression Id. */
  int NEWP = 24;
  /** RegularExpression Id. */
  int TEMPO = 25;
  /** RegularExpression Id. */
  int TONE = 26;
  /** RegularExpression Id. */
  int ID = 27;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"Part\"",
    "\"Note\"",
    "\"1/4\"",
    "\"1/2\"",
    "\"1/1\"",
    "\"Compose\"",
    "\"Display\"",
    "\"Play\"",
    "\"To\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"|\"",
    "\":\"",
    "<NUMBER>",
    "\"Add Note\"",
    "\"New Song\"",
    "\"New Phrase\"",
    "\"Tempo\"",
    "<TONE>",
    "<ID>",
  };

}
