/* Generated By:JavaCC: Do not edit this line. MusyConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface MusyConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int PART = 5;
  /** RegularExpression Id. */
  int SONG = 6;
  /** RegularExpression Id. */
  int INSTRUMENT = 7;
  /** RegularExpression Id. */
  int BEAT = 8;
  /** RegularExpression Id. */
  int TITLE = 9;
  /** RegularExpression Id. */
  int CREATE = 10;
  /** RegularExpression Id. */
  int PLAY = 11;
  /** RegularExpression Id. */
  int EXIT = 12;
  /** RegularExpression Id. */
  int SEMICOLON = 13;
  /** RegularExpression Id. */
  int COMMA = 14;
  /** RegularExpression Id. */
  int LPAR = 15;
  /** RegularExpression Id. */
  int RPAR = 16;
  /** RegularExpression Id. */
  int LBRAC = 17;
  /** RegularExpression Id. */
  int RBRAC = 18;
  /** RegularExpression Id. */
  int PLUS = 19;
  /** RegularExpression Id. */
  int EQUALS = 20;
  /** RegularExpression Id. */
  int ID = 21;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\" \"",
    "\"\\r\"",
    "\"\\t\"",
    "\"\\n\"",
    "\"part\"",
    "\"song\"",
    "\"instrument\"",
    "\"beat\"",
    "\"title\"",
    "\"create\"",
    "\"play\"",
    "\"exit\"",
    "\";\"",
    "\",\"",
    "\"(\"",
    "\")\"",
    "\"{\"",
    "\"}\"",
    "\"+\"",
    "\"=\"",
    "<ID>",
  };

}
